default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password:
  timeout: 5000
  port: 5432
  host: localhost

development:
  <<: *default
  database: epix_development

test:
  <<: *default
  database: epix_test

staging:
  <<: *default
  database: epix_staging

production:
  <<: *default
  database: epix_production

secondbase:
  development:
    <<: *default
    database: sapi_development

  test:
    <<: *default
    database: sapi_test

  staging:
    <<: *default
    database: sapi_staging

  production:
    <<: *default
    database: sapi_production
